### ISSUE TITLE
Product Status

### ISSUE THREAD

**Issue by samhamilton** [moqui/mantle#17]
Hey David! 

In mantle.product.Product you have the a relationship defined to moqui.basic.StatusItem for statusId but I am unable to find the corresponding status, if this is on a TODO list somewhere, applogies, I have not spotted it.

Thanks
Sam

**Comment by jonesde** [comment]
There are a few like this with a statusId placeholder, but no statuses in use yet. Most of the main entities have a statusId just because it is often useful to have, especially for custom code.
