### ISSUE TITLE
product.maintenance.AssetMeter - Visual Check and Inspections (yes/no)

### ISSUE THREAD

**Issue by ronankeane** [moqui/mantle#53]
In installation and service (maintenance) commissioning, visual checks and inspections would be very common, and included alongside meter readings. Currently a boolean yes-no response cannot be encompassed as meterValue is type 'number-decimal'. While this does stretch the terminology currently used of 'meter' to encompass 'check', it would be rare not to need to record these kind of observations.

**Comment by jonesde** [comment]
The approach I'd recommend is a AssetMeter record with no meterValue and a readingReasonEnumId that represents a check as opposed to reading a value.
