### ISSUE TITLE
mantle-udm data load error

### ISSUE THREAD

**Issue by gagaboy** [moqui/mantle#55]
In the ZapPayrollTaxDemoData.xml line 31 and line 201,the field "taxAuthPartyId" in entity "TaxAuthority"should not be none.When data load,there is a error.

**Comment by gagaboy** [comment]
My fault，the entity definition has been changed,but the db schema has not changed.The pk field is changed.Is there any other check mechanism to avoid this case or point to the developer ??

**Comment by gagaboy** [comment]
May be some check between the db table schema and the entity definition when load data??

**Comment by jonesde** [comment]
Entities that haven't been used yet in Mantle will change quite a bit while I'm working on functionality related to them, and right now I'm doing the first work based on the Human Resources entities, aside from EmplPositionClass and RateAmount which are being used related to tracking work and how much to pay and/or be paid for the work.

For more significant changes I would like to have change information in the entity definitions and additional functionality as need to update the database schema and even adjust data if needed between version updates (or call outs if we can get something like LiquiBase to handle this). This hasn't been done yet, and I couldn't comment on when I might work on it, but it would be great to have some solution like this to avoid more manual means of migrating schema and data from one release to another.

Even when this is in place, and definitely now, if you are updating regularly from git and are doing development (as opposed to updating a production system) then I'd recommend deleting your database and starting fresh frequently (i.e. "gradle cleanAll load" if you are using H2).

There have been some discussions about this on LinkedIn, which would be good to look at and a good place to start a new discussion if this is something you are interested in.
