### ISSUE TITLE
the entity CommunicationEventContent lost field partyId

### ISSUE THREAD

**Issue by gagaboy** [moqui/mantle#57]
there's a relationship 
```
< relationship type="one" related-entity-name="mantle.party.Party"/> 
```
in the CommunicationEventContent entity definition ,but lost the field define
```
<field name="partyId" type="id" />
```

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #7ed94d1. I removed the Party relationship as there is no need for one on this entity (but there is a userId that was missing its relationship).
